FROM python:3.10

WORKDIR /app

COPY  requirements.txt /requirements.txt

RUN python -m venv env

RUN /bin/bash -c "source env/bin/activate"

RUN pip install --no-cache-dir -r /requirements.txt

COPY . .

RUN chmod a+x bin/run.sh

EXPOSE 8000

ENTRYPOINT [ "bin/run.sh" ]